Repository liquisbert/git-training-NN, pull requests merged in 2021-07, with the labels that each got.

#1 Laskar
  notes.txt
Labels: bug, duplicate

#3 Harold
  index.html
Labels: bug, documentation

#5 Ruddy
  Ruddy/1.html
Labels: duplicate
